//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("MailService", "FK_MailService_Sending_Queue_Config", "MailService_Config", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ePortal.MailService.Model.MailService_Config), "MailService_Sending_Queue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ePortal.MailService.Model.MailService_Sending_Queue), true)]
[assembly: EdmRelationshipAttribute("MailService", "FK_MailService_Log_Sending_Queue", "MailService_Sending_Queue", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ePortal.MailService.Model.MailService_Sending_Queue), "MailService_Sended_Log", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ePortal.MailService.Model.MailService_Sended_Log), true)]

#endregion

namespace ePortal.MailService.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class MailServiceContainer : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“MailServiceContainer”部分中的连接字符串初始化新 MailServiceContainer 对象。
        /// </summary>
        public MailServiceContainer() : base("name=MailServiceContainer", "MailServiceContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MailServiceContainer 对象。
        /// </summary>
        public MailServiceContainer(string connectionString) : base(connectionString, "MailServiceContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MailServiceContainer 对象。
        /// </summary>
        public MailServiceContainer(EntityConnection connection) : base(connection, "MailServiceContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MailService_Config> MailService_Config
        {
            get
            {
                if ((_MailService_Config == null))
                {
                    _MailService_Config = base.CreateObjectSet<MailService_Config>("MailService_Config");
                }
                return _MailService_Config;
            }
        }
        private ObjectSet<MailService_Config> _MailService_Config;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MailService_Sended_Log> MailService_Sended_Log
        {
            get
            {
                if ((_MailService_Sended_Log == null))
                {
                    _MailService_Sended_Log = base.CreateObjectSet<MailService_Sended_Log>("MailService_Sended_Log");
                }
                return _MailService_Sended_Log;
            }
        }
        private ObjectSet<MailService_Sended_Log> _MailService_Sended_Log;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MailService_Sending_Queue> MailService_Sending_Queue
        {
            get
            {
                if ((_MailService_Sending_Queue == null))
                {
                    _MailService_Sending_Queue = base.CreateObjectSet<MailService_Sending_Queue>("MailService_Sending_Queue");
                }
                return _MailService_Sending_Queue;
            }
        }
        private ObjectSet<MailService_Sending_Queue> _MailService_Sending_Queue;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 MailService_Config EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMailService_Config(MailService_Config mailService_Config)
        {
            base.AddObject("MailService_Config", mailService_Config);
        }
    
        /// <summary>
        /// 用于向 MailService_Sended_Log EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMailService_Sended_Log(MailService_Sended_Log mailService_Sended_Log)
        {
            base.AddObject("MailService_Sended_Log", mailService_Sended_Log);
        }
    
        /// <summary>
        /// 用于向 MailService_Sending_Queue EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMailService_Sending_Queue(MailService_Sending_Queue mailService_Sending_Queue)
        {
            base.AddObject("MailService_Sending_Queue", mailService_Sending_Queue);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MailService", Name="MailService_Config")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MailService_Config : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MailService_Config 对象。
        /// </summary>
        /// <param name="sysID">SysID 属性的初始值。</param>
        /// <param name="user">User 属性的初始值。</param>
        /// <param name="pwd">Pwd 属性的初始值。</param>
        /// <param name="sMTPClient">SMTPClient 属性的初始值。</param>
        /// <param name="port">Port 属性的初始值。</param>
        public static MailService_Config CreateMailService_Config(global::System.String sysID, global::System.String user, global::System.String pwd, global::System.String sMTPClient, global::System.Int32 port)
        {
            MailService_Config mailService_Config = new MailService_Config();
            mailService_Config.SysID = sysID;
            mailService_Config.User = user;
            mailService_Config.Pwd = pwd;
            mailService_Config.SMTPClient = sMTPClient;
            mailService_Config.Port = port;
            return mailService_Config;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SysID
        {
            get
            {
                return _SysID;
            }
            set
            {
                if (_SysID != value)
                {
                    OnSysIDChanging(value);
                    ReportPropertyChanging("SysID");
                    _SysID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SysID");
                    OnSysIDChanged();
                }
            }
        }
        private global::System.String _SysID;
        partial void OnSysIDChanging(global::System.String value);
        partial void OnSysIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pwd
        {
            get
            {
                return _Pwd;
            }
            set
            {
                OnPwdChanging(value);
                ReportPropertyChanging("Pwd");
                _Pwd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pwd");
                OnPwdChanged();
            }
        }
        private global::System.String _Pwd;
        partial void OnPwdChanging(global::System.String value);
        partial void OnPwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SMTPClient
        {
            get
            {
                return _SMTPClient;
            }
            set
            {
                OnSMTPClientChanging(value);
                ReportPropertyChanging("SMTPClient");
                _SMTPClient = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SMTPClient");
                OnSMTPClientChanged();
            }
        }
        private global::System.String _SMTPClient;
        partial void OnSMTPClientChanging(global::System.String value);
        partial void OnSMTPClientChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private global::System.Int32 _Port;
        partial void OnPortChanging(global::System.Int32 value);
        partial void OnPortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Authenticate
        {
            get
            {
                return _Authenticate;
            }
            set
            {
                OnAuthenticateChanging(value);
                ReportPropertyChanging("Authenticate");
                _Authenticate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Authenticate");
                OnAuthenticateChanged();
            }
        }
        private Nullable<global::System.Int32> _Authenticate;
        partial void OnAuthenticateChanging(Nullable<global::System.Int32> value);
        partial void OnAuthenticateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SSL
        {
            get
            {
                return _SSL;
            }
            set
            {
                OnSSLChanging(value);
                ReportPropertyChanging("SSL");
                _SSL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SSL");
                OnSSLChanged();
            }
        }
        private Nullable<global::System.Boolean> _SSL;
        partial void OnSSLChanging(Nullable<global::System.Boolean> value);
        partial void OnSSLChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MailService", "FK_MailService_Sending_Queue_Config", "MailService_Sending_Queue")]
        public EntityCollection<MailService_Sending_Queue> MailService_Sending_Queue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MailService_Sending_Queue>("MailService.FK_MailService_Sending_Queue_Config", "MailService_Sending_Queue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MailService_Sending_Queue>("MailService.FK_MailService_Sending_Queue_Config", "MailService_Sending_Queue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MailService", Name="MailService_Sended_Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MailService_Sended_Log : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MailService_Sended_Log 对象。
        /// </summary>
        /// <param name="logID">LogID 属性的初始值。</param>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="subject">Subject 属性的初始值。</param>
        /// <param name="to">To 属性的初始值。</param>
        /// <param name="cC">CC 属性的初始值。</param>
        /// <param name="bcc">Bcc 属性的初始值。</param>
        /// <param name="body">Body 属性的初始值。</param>
        /// <param name="sysID">SysID 属性的初始值。</param>
        /// <param name="sendTime">SendTime 属性的初始值。</param>
        public static MailService_Sended_Log CreateMailService_Sended_Log(global::System.Int64 logID, global::System.Int64 id, global::System.String subject, global::System.String to, global::System.String cC, global::System.String bcc, global::System.String body, global::System.String sysID, global::System.DateTime sendTime)
        {
            MailService_Sended_Log mailService_Sended_Log = new MailService_Sended_Log();
            mailService_Sended_Log.LogID = logID;
            mailService_Sended_Log.ID = id;
            mailService_Sended_Log.Subject = subject;
            mailService_Sended_Log.To = to;
            mailService_Sended_Log.CC = cC;
            mailService_Sended_Log.Bcc = bcc;
            mailService_Sended_Log.Body = body;
            mailService_Sended_Log.SysID = sysID;
            mailService_Sended_Log.SendTime = sendTime;
            return mailService_Sended_Log;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 LogID
        {
            get
            {
                return _LogID;
            }
            set
            {
                if (_LogID != value)
                {
                    OnLogIDChanging(value);
                    ReportPropertyChanging("LogID");
                    _LogID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LogID");
                    OnLogIDChanged();
                }
            }
        }
        private global::System.Int64 _LogID;
        partial void OnLogIDChanging(global::System.Int64 value);
        partial void OnLogIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String To
        {
            get
            {
                return _To;
            }
            set
            {
                OnToChanging(value);
                ReportPropertyChanging("To");
                _To = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("To");
                OnToChanged();
            }
        }
        private global::System.String _To;
        partial void OnToChanging(global::System.String value);
        partial void OnToChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CC
        {
            get
            {
                return _CC;
            }
            set
            {
                OnCCChanging(value);
                ReportPropertyChanging("CC");
                _CC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CC");
                OnCCChanged();
            }
        }
        private global::System.String _CC;
        partial void OnCCChanging(global::System.String value);
        partial void OnCCChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bcc
        {
            get
            {
                return _Bcc;
            }
            set
            {
                OnBccChanging(value);
                ReportPropertyChanging("Bcc");
                _Bcc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bcc");
                OnBccChanged();
            }
        }
        private global::System.String _Bcc;
        partial void OnBccChanging(global::System.String value);
        partial void OnBccChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SysID
        {
            get
            {
                return _SysID;
            }
            set
            {
                OnSysIDChanging(value);
                ReportPropertyChanging("SysID");
                _SysID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SysID");
                OnSysIDChanged();
            }
        }
        private global::System.String _SysID;
        partial void OnSysIDChanging(global::System.String value);
        partial void OnSysIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SendTime
        {
            get
            {
                return _SendTime;
            }
            set
            {
                OnSendTimeChanging(value);
                ReportPropertyChanging("SendTime");
                _SendTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SendTime");
                OnSendTimeChanged();
            }
        }
        private global::System.DateTime _SendTime;
        partial void OnSendTimeChanging(global::System.DateTime value);
        partial void OnSendTimeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MailService", "FK_MailService_Log_Sending_Queue", "MailService_Sending_Queue")]
        public MailService_Sending_Queue MailService_Sending_Queue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailService_Sending_Queue>("MailService.FK_MailService_Log_Sending_Queue", "MailService_Sending_Queue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailService_Sending_Queue>("MailService.FK_MailService_Log_Sending_Queue", "MailService_Sending_Queue").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MailService_Sending_Queue> MailService_Sending_QueueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailService_Sending_Queue>("MailService.FK_MailService_Log_Sending_Queue", "MailService_Sending_Queue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MailService_Sending_Queue>("MailService.FK_MailService_Log_Sending_Queue", "MailService_Sending_Queue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MailService", Name="MailService_Sending_Queue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MailService_Sending_Queue : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MailService_Sending_Queue 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="subject">Subject 属性的初始值。</param>
        /// <param name="to">To 属性的初始值。</param>
        /// <param name="cC">CC 属性的初始值。</param>
        /// <param name="bcc">Bcc 属性的初始值。</param>
        /// <param name="body">Body 属性的初始值。</param>
        /// <param name="sysID">SysID 属性的初始值。</param>
        public static MailService_Sending_Queue CreateMailService_Sending_Queue(global::System.Int64 id, global::System.String subject, global::System.String to, global::System.String cC, global::System.String bcc, global::System.String body, global::System.String sysID)
        {
            MailService_Sending_Queue mailService_Sending_Queue = new MailService_Sending_Queue();
            mailService_Sending_Queue.ID = id;
            mailService_Sending_Queue.Subject = subject;
            mailService_Sending_Queue.To = to;
            mailService_Sending_Queue.CC = cC;
            mailService_Sending_Queue.Bcc = bcc;
            mailService_Sending_Queue.Body = body;
            mailService_Sending_Queue.SysID = sysID;
            return mailService_Sending_Queue;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String To
        {
            get
            {
                return _To;
            }
            set
            {
                OnToChanging(value);
                ReportPropertyChanging("To");
                _To = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("To");
                OnToChanged();
            }
        }
        private global::System.String _To;
        partial void OnToChanging(global::System.String value);
        partial void OnToChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CC
        {
            get
            {
                return _CC;
            }
            set
            {
                OnCCChanging(value);
                ReportPropertyChanging("CC");
                _CC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CC");
                OnCCChanged();
            }
        }
        private global::System.String _CC;
        partial void OnCCChanging(global::System.String value);
        partial void OnCCChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bcc
        {
            get
            {
                return _Bcc;
            }
            set
            {
                OnBccChanging(value);
                ReportPropertyChanging("Bcc");
                _Bcc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bcc");
                OnBccChanged();
            }
        }
        private global::System.String _Bcc;
        partial void OnBccChanging(global::System.String value);
        partial void OnBccChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SysID
        {
            get
            {
                return _SysID;
            }
            set
            {
                OnSysIDChanging(value);
                ReportPropertyChanging("SysID");
                _SysID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SysID");
                OnSysIDChanged();
            }
        }
        private global::System.String _SysID;
        partial void OnSysIDChanging(global::System.String value);
        partial void OnSysIDChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MailService", "FK_MailService_Sending_Queue_Config", "MailService_Config")]
        public MailService_Config MailService_Config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailService_Config>("MailService.FK_MailService_Sending_Queue_Config", "MailService_Config").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailService_Config>("MailService.FK_MailService_Sending_Queue_Config", "MailService_Config").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MailService_Config> MailService_ConfigReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MailService_Config>("MailService.FK_MailService_Sending_Queue_Config", "MailService_Config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MailService_Config>("MailService.FK_MailService_Sending_Queue_Config", "MailService_Config", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MailService", "FK_MailService_Log_Sending_Queue", "MailService_Sended_Log")]
        public EntityCollection<MailService_Sended_Log> MailService_Sended_Log
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MailService_Sended_Log>("MailService.FK_MailService_Log_Sending_Queue", "MailService_Sended_Log");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MailService_Sended_Log>("MailService.FK_MailService_Log_Sending_Queue", "MailService_Sended_Log", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
